### ISSUE TITLE
Deploy failed

### ISSUE THREAD

**Issue by YunL0ngLee** [Phala-Network/runtime-bridge#21]
![image](https://user-images.githubusercontent.com/30599323/123507888-c6000900-d69e-11eb-80a4-884df5e34de1.png)

**Comment by krhougs** [comment]
We are currently refactoring the whole mining implement on the chain side, please follow the new docs when https://github.com/Phala-Network/runtime-bridge/pull/20 is merged.

**Comment by YunL0ngLee** [comment]
> We are currently refactoring the whole mining implement on the chain side, please follow the new docs when #20 is merged.

ok，thanks

**Comment by YunL0ngLee** [comment]
![image](https://user-images.githubusercontent.com/30599323/123599640-69305a00-d828-11eb-8e44-913e4b2b71b9.png)

It`s failed when i used the new version.

**Comment by amphineko** [comment]
Hi @YunL0ngLee 

Make sure that you have purged your local image cache of Docker, removed all your previous containers.

Please also provide more details, including your current Docker image version.

**Comment by sidealice** [comment]
after  Step 12/12 same error:
 Cannot find package 'encoding-down' imported from /opt/app/src/io/db.js

after build again got erro:
Cannot find package 'bunyan' imported from /opt/app/src/utils/logger.js

**Comment by YunL0ngLee** [comment]
> Hi @YunL0ngLee
> 
> Make sure that you have purged your local image cache of Docker, removed all your previous containers.
> 
> Please also provide more details, including your current Docker image version.

I have soled it，but get a new problem。
![image](https://user-images.githubusercontent.com/30599323/123728794-78fe7b80-d8c6-11eb-8b7f-e6652d4c76df.png)
It should wait the RPC interface implement...

**Comment by YunL0ngLee** [comment]
> after Step 12/12 same error:
> Cannot find package 'encoding-down' imported from /opt/app/src/io/db.js
> 
> after build again got erro:
> Cannot find package 'bunyan' imported from /opt/app/src/utils/logger.js

Step1:Clean your local docker images,download new version.
Step2:Modify the Dockerfile item 'python' to 'python3'.
Setp3:Rebuild docker imgae.

**Comment by YunL0ngLee** [comment]
> Hi @YunL0ngLee
> 
> Make sure that you have purged your local image cache of Docker, removed all your previous containers.
> 
> Please also provide more details, including your current Docker image version.

Has the developer tested it？I don't think perfected it yet，right？

**Comment by sidealice** [comment]
Cannot find package 'encoding-down' imported from /opt/app/src/io/db.js

same problem after your suggested.

**Comment by sidealice** [comment]
> > after Step 12/12 same error:
> > Cannot find package 'encoding-down' imported from /opt/app/src/io/db.js
> > after build again got erro:
> > Cannot find package 'bunyan' imported from /opt/app/src/utils/logger.js
> 
> Step1:Clean your local docker images,download new version.
> Step2:Modify the Dockerfile item of 'python' to 'python3'.
> Setp3:Rebuild docker imgae.

Cannot find package 'encoding-down' imported from /opt/app/src/io/db.js

same problem after your suggested.

**Comment by krhougs** [comment]
> > > after Step 12/12 same error:
> > > Cannot find package 'encoding-down' imported from /opt/app/src/io/db.js
> > > after build again got erro:
> > > Cannot find package 'bunyan' imported from /opt/app/src/utils/logger.js
> > 
> > 
> > Step1:Clean your local docker images,download new version.
> > Step2:Modify the Dockerfile item of 'python' to 'python3'.
> > Setp3:Rebuild docker imgae.
> 
> Cannot find package 'encoding-down' imported from /opt/app/src/io/db.js
> 
> same problem after your suggested.

You did not clear previous build step cache.

**Comment by sidealice** [comment]
> > > > after Step 12/12 same error:
> > > > Cannot find package 'encoding-down' imported from /opt/app/src/io/db.js
> > > > after build again got erro:
> > > > Cannot find package 'bunyan' imported from /opt/app/src/utils/logger.js
> > > 
> > > 
> > > Step1:Clean your local docker images,download new version.
> > > Step2:Modify the Dockerfile item of 'python' to 'python3'.
> > > Setp3:Rebuild docker imgae.
> > 
> > 
> > Cannot find package 'encoding-down' imported from /opt/app/src/io/db.js
> > same problem after your suggested.
> 
> You did not clear previous build step cache.

I removed all images and containers before. 

To clear the cache:docker system prune , correct?

**Comment by sidealice** [comment]
After  docker system prune  same error.
