### ISSUE TITLE
websocket connection failed

### ISSUE THREAD

**Issue by aixiaoo** [Phala-Network/runtime-bridge#22]
![](https://i.loli.net/2021/06/28/YShZGkBqyNi3Frb.png)
It`s connection failed

**Comment by aixiaoo** [comment]
https://i.loli.net/2021/06/28/YShZGkBqyNi3Frb.png

**Comment by amphineko** [comment]
Your WebSocket endpoint is currently the default placeholder and not configured.

You should modify your `docker-compose.yml` before starting.

https://github.com/Phala-Network/runtime-bridge/blob/37022bb73eb99bf64e1e5561475c63e96cf13899/docker/testing/bridge/docker-compose.example.yml#L19
https://github.com/Phala-Network/runtime-bridge/blob/37022bb73eb99bf64e1e5561475c63e96cf13899/docker/testing/bridge/docker-compose.example.yml#L34

**Comment by aixiaoo** [comment]
Yes now I have modified my docker-compose.yml file, but I have a problem with the exit code 255

This is using my local websocket
![Snipaste_2021-06-29_13-53-59](https://user-images.githubusercontent.com/26303150/123745791-57f85380-d8e3-11eb-91b9-8575196f907f.png)

This is using Poc4 websocket
![Snipaste_2021-06-29_13-52-01](https://user-images.githubusercontent.com/26303150/123745932-870ec500-d8e3-11eb-8d5d-7ebded5ffb42.png)

**Comment by YunL0ngLee** [comment]
> Yes now I have modified my docker-compose.yml file, but I have a problem with the exit code 255
> 
> This is using my local websocket
> ![Snipaste_2021-06-29_13-53-59](https://user-images.githubusercontent.com/26303150/123745791-57f85380-d8e3-11eb-91b9-8575196f907f.png)
> 
> This is using Poc4 websocket
> ![Snipaste_2021-06-29_13-52-01](https://user-images.githubusercontent.com/26303150/123745932-870ec500-d8e3-11eb-8d5d-7ebded5ffb42.png)

![image](https://user-images.githubusercontent.com/30599323/123792806-9d347980-d913-11eb-9643-7cc6afa080ac.png)
The RPC interface is`nt implement...

**Comment by krhougs** [comment]
Explained in https://github.com/Phala-Network/runtime-bridge/wiki/%E7%9F%BF%E6%B1%A0%E5%8D%8F%E8%AE%AE%E5%BC%80%E5%8F%91%E8%80%85%E6%96%87%E6%A1%A3%EF%BC%88zh_CN%EF%BC%89
