### ISSUE TITLE
这个库是官方程序员在维护吗，为什么问题没解决就关闭？

### ISSUE THREAD

**Issue by sidealice** [Phala-Network/runtime-bridge#27]
进来的都是程序员。按照你这个文档流程不对，如果要清除doker缓存，你就应该写怎么清除。这难道是用户的问题吗？
工具链的使用说明不是你懒惰的借口。 你的依赖自己运行过了吗？

如果一步步按照你说的都没问题，我们专注的点就是开发，而不是在那里沟通工具链。这违背了工具的目标。你看看我和你讨论问题几次了，你回答的是什么？

如果只是告诉一个命令就能解决问题了，为什么要浪费大家的时间。 这样做，怎么做的好生态环境。
可悲。

**Comment by sidealice** [comment]
我想了一下，你的问题归根到底是态度问题。

**Comment by krhougs** [comment]
二次开发还是有准入门槛的哈。

**Comment by h4x3rotab** [comment]
欢迎在issue区讨论和工程直接相关的问题。对于其他讨论，欢迎移步Phala论坛，或者Docker支持社区。
