### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by sidealice** [Phala-Network/runtime-bridge#31]
原因：
1 docker适合确保开发系统环境。 更偏向于测试和运维。 你的readme里面更多的是说了怎么运行（虽然我也没有运行成功），其实这个readme应该多一些逻辑和流程。当然看代码也可以，不过那样的话你连readme都干脆别写了，因为这个库是给开发的。这样和民间开源有啥区别，官方开源是给一个hello world，然后大家可以扩展和增强。并不是拿你的代码直接用，或者按照你的思路就僵化了。
例如： 你用了redis，是否可以抽象db/queue类，通过抽象类来进行整个库其他功能的调用，这样可以更换。 另外你的代码里面哪些是配置的常量比如FETCH_QUEUE_CONCURRENT默认是50，比较重要的应该说明一下。这是你要考虑到的，因为你是官方一个起的头。你提供的其实是架构，我们看完你的代码更快的自己实现一个，而不是看完你的代码，去思考你为什么这样去做（你也没有注释）。当然你写代码没有任何自己的热情和理想，重点的地方不做任何注释也不要紧，可能开发的人喜欢来回重写省了注释。 

2 代码在一个repo，发生变动和维护，更容易看到关注的点的变化。你是用node开发的，那么你这个node做了一个包，对外暴露一些接口和类，我们进行扩展重写。约定好一些规则，避免以后你重写类影响了向下兼容。 把docker分离出这个repo，放在另外一个repo用于运行调用代码。 这样逻辑会清晰一些。 至少这样一进来的人可以知道你这个代码就是一个node项目，不用去思考是不是有go，rust，dart，python依赖等。清晰很重要。

3 二次开发的关键是rpc接口的说明和调用规则。这个在repo里面并没有注释和说明。我后面详细提问一下。

4 fetch做了哪些事情，你说的 fetch reorganizes blocks into formats that pRuntime consumes. 这句话后面至少应该跟上pRuntime consume的规范格式是什么，链接引用也可以。毕竟官方repo，这么随意，完全不在乎给谁看。
另外requires at least 10Mbps bandwidth for intranet I/O when synching blocks from the chain 这个是怎么测算的，调用频次没有明确，应该补上你的估计想法基于每个报文请求平均大小和频次得出的结论，这样评估带宽的时候会更科学一点，因为这样可以考虑上限的场景。而且不仅仅是带宽，还有并发的情景。

代码里面：'sync_block', 'compute_window' 这两个rpc请求接口，是否可以解释一下定义。
window里面waitForBlobRangeEnd有重试机制，但是如果重试5次以后有问题，看代码是没有处理的。如果网络不稳定，5次以后也不应该放弃。应该标记到一个表管理，等恢复网络以后重试。网络请求可以封装一个类吗，rpc，websocket，http这些都在一起，重新请求也包含在里面。我看到你后面lifecycle也是这个问题。

5 Lifecycle Manager 是管理worker的。这部分rpc的也可以整理提供一下吗？
bug：代码里面：MINIUM_BALANCE 没有读取常量 ，直接提示了'Balance must be greater than 10000 PHA!'
shouldSkipRa 是什么常量？ 是测试网用的吗？
由于用的是event来做触发，可以文档集中一下每个event吗，因为比较离散。我看到调用的是对应trade的action。既然你都用了dispatchTx了，不能所有的都基于dispatch吗
比如：
`
  const waitUntilSynched = await startSyncBlob(runtime)
  await waitUntilSynched()
  logger.info(workerBrief, 'waitUntilSynched done.')
  if (runtime.skipRa) {
    await dispatchTx({
      action: 'START_MINING_INTENTION',
      payload: {
        worker,
      },
    })
  }
`
startSyncBlob这部分不能这样改造吗
`
    await dispatch({
      action: 'START_SYNC_BLOB',
      payload: {
        runtime,
      },
    })
`
这样我们二次开发的时候都不用入侵，这样你只需要文档化所有的dispatch部分，二次开发的时候我们扩展会方便很多。

6 是否可以做核心的单元测试的代码，这样避免你改了也不知道是不是你改错，还是我们二次开发的时候错了。这个应该是一个开源项目良好的根基。

7 目前的模块是fetch，lifecycle和trade。 我觉得fetch既然定位是数据转换，应该重点说明格式转换的差异点。这样任何语言都可以实现这个转换，并不是只能用node。 lifecycle如果是作为和worker沟通的中间件api， 那么有哪几个api是什么也应该说明和罗列rpc的信息，一方面是请求链的api（trade应该做的），一方面是和worker沟通的api（lifecycle应该做的），虽然你定位trade是relay， 那么lifecycle没有relay吗？ 因为最后二次开发的要有一个ui系统和worker打交道。这个打交道的api后端肯定是管理矿工的各种功能，这个功能既不可能按照现在的lifecycle也不可能按照现在的trade，只能是一个结合两者的。 因此分离两者不如合并，把涉及到链上请求的抽象一起，涉及到非链的抽象一起。如果更具体的话，抽象可以具体到 worker，transaction，lottery 等。 这样二次开发的时候只需要关注的点是 lottery和他的状态机， 你是什么框架或者什么语言都是容易移植的。 

比如你现在写的方法是context来做传递， 如果你抽象的对象是worker， 那么worker的行为其实是有限的。每个行为都有状态机， 这样你并不是传递这么多context给到worker （很多信息是多余的）。 start mining 的情况下在你的演示情况下是需要api到链上，但是二次开发的时候会更新数据库里面一个标识。 这个时候worker 类实例worker.startMining(payload)=>dispatchTx('START_MINING_INTENTION' ,payload)。 而且写清楚payload的结构我觉得会比较有利于二次开发。 

再举一个例子：
`
  await setAccount(dispatchTx, worker, onChainState)
`
是否可以改为
`
payload=onChainState
worker.setAccount(payload)=>dispatchTx('WORKER_SET_ACCOUNT' ,payload)
`

类似这种情况还比较多， 我的意思是你抽象类了以后，二次开发的关注点在类对象的抽象上。不是你的context。 你的context需要单元测试去确保。 不然后面不好维护的。

随着后续lottery这种出来，目前这种代码怎么操作呢。如果是质押上了， 提名者，验证者和存款这些有更多关联关系的呢，靠context不断加吗？  你对象抽象的时候，不仅仅为了开发扩展。 其实也是保障了其他语言开发的时候去移植更快一些。 回到开头说的， 如果你抽象封装了数据库/队列类， 我们可以用持久化的数据库或者队列存储来替换redis， 有的场景下是需要考虑非易失存储的。 

看了你的代码也有学习。 但是你这完全可以做的更好，并不是为了完成工作，而是把这个事情用理想去做好，来不及做你就把能做好的做好，剩下来的说清楚，看看社区有没有资源去做，你这样赶工最后还是要重做的。我看了block-chain的同事就做的很好，虽然有可能很多事参考了rust社区的代码树，但是我觉得有没有花心思还是能看得出来的。 

文档没有和注释不能偷懒，这不一定是写给小白看的，可能你某个fix的注释就是几个小时的思考。 没有这个注释，我们可能也会花很多时间问你，你花时间回答还不如写清楚注释。

**Comment by skysummerice** [comment]
非常感谢您对Phala Network的关注和建议。目前Phala正在招聘中英文语种的技术支持工程师，欢迎您关注。详情请联系hire@phala.network

**Comment by krhougs** [comment]
感谢您在心态平和的情况下花时间写下这篇长文。如果您没有像在之前的issue中在没有提供任何可供调试的有效信息的情况下就乱下断言并上纲上线的话，我们也不可以直接关闭您的issue。

对于 https://github.com/Phala-Network/runtime-bridge/issues/25 ，鉴于CI每次触发运行时会创建一个全新且干净的环境，本地测试环境、本地开发环境、社区内其他成功编译案例以及CI环境中均没有复现你所说的情况且可以成功编译。且您在提出问题的时候没有带上任何有用的、可以协助debug的有效信息，仅在你的环境中试出未经证实可用的解决方法的情况下就进行了断言。

对于 https://github.com/Phala-Network/runtime-bridge/issues/24 ，由于你没有给出任何环境信息，我只能推断出现这种情况有两种可能：
- 你使用了开发环境的docker镜像且在其中没有安装依赖
- 你使用了测试环境的docker镜像但是没有正确配置好volume

基于以上两点，我才建议您先去学习node和docker的基本概念和用法。

希望您能了解到理解和尊重是相互的，对于这个项目，我们没有精力和义务提供无偿的入门技术支持。

对于本文提到的问题：
1. 这个项目提供的是一个符合云原生规范的提供矿机集群管理RPC API的服务，最终目的是不需要开发者进行本项目进行代码修改，直接将本项目部署在Kubernetes中即可提供矿机管理的RPC。我们的确正在Staking等的相关项目，但不会将这些东西耦合进一个项目中。
2. 由于需要配合链端近期的挖矿机制重构，RPC的API设计还没有稳定，暂时没有办法提供单元测试和API文档。您所提到的项目管理相关的事宜其实都在我们内部的to-do list中，请耐心等待更新。
3. 您所提到的class抽象其实是我们在权衡之后决定不采用的设计模式。我们将各个组件进行了解耦合，并export了与context无关的pure function。请不要将眼光限制于Java项目的思维中，您可能不太了解Node的包管理方式且对FP编程风格缺乏了解。
4. 队列不持久化是因为大部分内部操作带有实时性，且状态机会从链上recover状态。如果您有队列持久化储存需求，可以开启redis的持久化模式。
5. 建议您提问题的时候尽量一次性带上有用的信息，且讨论时尽量减少一些爹味的指责，多一些友善的讨论。由于我们的团队不鼓励加班，因此工作时间精力有限，请理解 : )

**Comment by sidealice** [comment]
谢谢反馈， 关于纯函数，我觉得也不是万能的，我的建议是考虑到你们框架会不断扩展和完善的角度。
1 你提到了你提供的这个是不需要修改的，那么我觉得其实是本质我们理解出问题了。我以为你说的二次开发是我们要修改实现，你们提供的是一个框架。 

2  谢谢。

3 什么情况是用纯函数合适，什么情况不是。包括数据持久化也一样。
对于runtime和链上的交互，你用什么都行但是你要满足可维护可扩展。 对于runtime和矿机或者应用系统的关系，我并不是因为java的思维来考虑你的结构设计，是从框架来考虑的，我觉得即便抽象了角色，用纯函数也可以运行。纯函数和抽象对象没有矛盾。 我建议数据库你抽象封装，是为了以后可以换其他消息系统，哪怕是自己做一个消息系统，你抽象以后也好控制，而且以后功能的变化也能够评估。 export了与context无关的pure function，没问题，我能看得懂，我看的不清楚的部分是并不是所有的context都解耦合了。在context里面定义的内容要什么结构，在其他模块里面也一样复制了一份。比如 a(context)  把context一层层传递下去。 首先，其他模块知不知道context有效的结构？ 目前的代码没有去验证context的有效性，扩展到越来越多的功能， 最早的定义修改，你其他context相关涉及到的代码怎么更新？ 
这个问题现在我也觉得不是大问题了，你提到了这个runtime不需要我们改代码。

4 数据库如果可以抽象我觉得比较好，因为可以实时消息队列的有很多。持久化的需要是我觉得会和外部系统交互，两者的关联关系需要持久化。而且有很多请求和查询在业务场景下是有事务关系的。当然这些部分可以不放在runtime里面，由第三方来处理。但是目前没有rpc协议的定义，所以我有这个顾虑。

5 都是开源的不存在谁欠谁，所以我不可能一上来就指责你。你看看你怎么处理提问的，这个因在你身上。 我建议你看下大部分要做好的github项目，提问的issue 没有解决提问者的情况下是关闭的吗？ 你解决我的问题说docker的问题你不负责教学， 其实你说一下哪条命令就可以了。 事实上最后问题是你没有提到运行环境也需要运行npm install 。 你按照你的文档你觉得没问题，但是这是你写的。别人执行遇到问题，你第一个不应该说没问题，你要问怎么遇到了问题。 然后这种问题的解决可以减少更多人问和遇到。  直接关闭了问题，我还是不能运行。 你觉得问题就解决了吗？

开源社区的目的是一起做，你这样还是自己一个人在做。 你提到加班。 我觉得你如果觉得是加班的话，你就别做现在的工作了， 本身就没有加班。 这是一种理念你明白吗？ 做好一个东西要的是理念，不是加班。 所以我才说态度有问题。算了，这个每个人的理解不一样， github的大部分项目你看那些开源5年以上还在频繁commit的，他觉得是加班吗？ 
区块链本身不是技术，更多的就是一种对经济政治和社会的思考。substrate为什么框架里面有议会治理，为什么要考虑到society。 做好这个东西需要你投入一些理想主义。

**Comment by sidealice** [comment]
我觉得我说的也过了。 也有很多项目其实做完就算交付完工，拿钱领工资就可以了。 我对你说的那些其实没什么意义，因为这些话加重了大家隔阂。 

非常感谢你的反馈，我看了文档现在很清晰，你说的也很中肯很有见地。 互相学习，由于经验和关注点不一样，我对你的系统肯定有很多错误的意见和理解。 在能够运行的基础上我再说才是合理的。

**Comment by krhougs** [comment]
3. 对于类型问题（也就是你认为的“抽象”），按照计划项目会在ReScript实现了async/await提案后迁移过去（由于我个人喜好的原因我不会使用TypeScript）。不同context传递过程中保持了immutable，扩展不会出现问题。
4. 由于Node.js是单线程模型，在考虑到性能的情况下，我们使用的RocksDb是kv数据库且不会过于依赖index，且此部分在我们的设计下不会出现需要频繁改动runtime-bridge内部数据类型的场景，按照场景拆分出读写函数完全满足需求。至于队列持久化，由于TEE执行环境和链上状态完全隔离，在意外停机后、重新检验状态前，塞进队列的操作都是无意义的。
5. 另外请您理解，这个项目目前只有我一个人维护，且涉及到与多个正在频繁进行设计变动的项目进行协作，不可能做到及时。目前我们团队对于这个项目的定位就是给有集成需要的Pro Developer提供支持，因此我们不认为我们有义务帮助用户进行入门教学（普通矿工侧有专人提供客服支持）。

以下言论仅代表我个人不代表团队：

您对开源协作的流程有严重的误解，此处由于观念不一就不深究了。但是，如果要较真的话，你的issue上来就是丢个截图什么都不说然后就指责我推代码之前没有测试，那我只能认为您在找茬。我对您这种不尊重他人的工作成果的同时要求他人像喂巨婴一样对待您后被拒绝因而上纲上线的行为特别反感。

希望您能理解，我们不是您的员工，不应该被您用那种语气呵斥。

每个人都有自己的生活。

**Comment by krhougs** [comment]
BTW，这个项目我能做到24小时即时响应任何问题，我只是单纯不想**服务你**而已你。

**Comment by sidealice** [comment]
3和4我说一下 你我角度不一样，我要考虑接入链的应用。所以我需要持久化的部分，这个疑问我觉得你说了这个库是你们运行，不需要我们二次开发我觉得就没有了。说明我们要二次开发，对接这个runtime就可以了。 这个我们的争论其实一开始是有矛盾的。 抽象对于我来说是为了架构可维护可扩展（而且我们的结构系统也不是完全在链上的），你们需不需要不重要，因为我们不需要二次开发runtime了。

5 你理解有问题，是不是你一个人维护不重要。重要的是不是无视反馈。 我第一个反馈你也没有问我解决了吗，你就关闭了。 那我再开一个我怎么问？ 我复制问题吗？

你的工作成果每个人都可以尊重也可以不尊重。这个是取决于你尊不尊重你自己的工作。 你看下我问你的问题，如果从一开始来看，我是尊重的。 后面为什么不尊重你觉得呢？从2009年开始，这么多开源项目我一个没有喷过。我到现在就喷了你。 你想想为什么？ 

我一直在和你说，问题没有解决不要关闭。 你每次都关， 我提出问题，你解决没解决你怎么知道呢？ 
最早的问题，你同事都说了。你的相对路径的配置不对，这个代码库有没有问题，你自己不信任别人提的问题，每次都觉得是不会用docker，我每次都说我清理了整个docker，换一个新的服务器都一样。 你不去帮忙解决问题的原因，责任推给我们看的人。 

你应该思考一下你自己做的这个库，到底有人在用吗？有没有人反馈问题。 没人反馈问题，谁来尊重你？
你的代码没人维护的了，你自己尊重你的代码吗？

你看一下issue，不是我一个人在说你的代码没有测试过了。https://github.com/Phala-Network/runtime-bridge/issues/21#issuecomment-870533521
你看下这个人说的，你觉得他想喷你吗？ 我觉得任何一个人都想喷。但是你觉得是大家不会用docker，可以你想过为什么要用docker吗？ 这么多开源项目都用docker，为什么就你这个有问题，如果你觉得不会docker，你连操作说明也不说，环境配置也不说，注意点也不说。 你这个项目完全靠猜。 这样你开源了，有谁会尊重你。

我不是为了引战。 你做的事情是花了时间的，但是你也要尊重我们，我们看你的代码，值得花时间看的，也有不值得花时间的。 你的结构是有问题的，你也不承认， 我尊重你。 我是说建议。  我给你提交issue 你花时间认真回复大家了吗。 之前那个问你的人，之后又问过任何一个问题吗， 大家发现你这种回答没有价值。

我就不大家弄的很矛盾了， 我现在不是要对你有什么意见。 我就是想研究透彻整个系统。 因为要做中间件和phala的系统对接整合， 我想你们说这个是矿池协议，那我就多花一点时间研究下，我们二次开发做一个自己可以对接的东西。 到你们这个库看了下，运行不了，花了一些时间排查（包括我发现怎么python没有改为python3等）。那么我就来提问，结果发现有人和我一样， 我问了你了， 你回答完了很好。 但是没想到你给关闭了问题， 那没关系我再问一次， 结果你一句话。  那现在我怎么办呢？ 你没想过是什么环境差异吗？ 你如果不关心这个，那这个docker有什么用，还不如直接本地开发。  那我本地开发吧， 也有问题。 并不是本地开发的友好代码。没有配置文件，环境变量我提交另外一个问题了。 

对了，关于语气问题。我想了下可能你是说我后面有几个issue， 不过你也可以看看你怎么发的吧。 什么小白啊，教学啊，这种我就不说了。 我的意思是，你没有做一个东西让我尊重的情况下，你说我小白，你值得我的呵斥，不论你是谁什么地位，你都应该被呵斥， 因为你没有尊重技术。
如果有人一点不懂，我也不会觉得帮他是在浪费时间。 因为他只要有意愿总会懂的。你如果每次遇到一个提问题的都假定是小白，那么问你问题的人可能很少甚至懒得问。 

开源社区做的东西不依赖于任何一个人，你的生活你继续过，但是另外一个人接了这个库可以继续上手，而不是重头再写。所以我提了这些意见，不过这些意见不用看了，因为你们觉得这个库并不需要二次开发了， 我觉得有了rpc协议，其实是不用改你们的代码的。要对接什么，只需要通过rpc请求。

附：https://github.com/Phala-Network/runtime-bridge/issues/21#issuecomment-870533521  我认真反馈了你，你回复了啥？ 需要尊重的开始吗？

**Comment by sidealice** [comment]
你只有一个人，如果你能最早解答一个人的问题（比如我），后面大家都节约了时间可以研究更重要的事情。 你看这个issue多浪费你时间？ 我觉得真的别认为别人是小白就一点都不理， 随手一个链接都可以。 因为你已经知道的和提问的人的信息是不对等的。你有同事，你已经对项目熟悉了，其他人要看需要你简单说一句，当然如果看了说明就不用问，谁都不会提交issue，就因为提交了。更说明很多人都有一样的问题。

**Comment by sidealice** [comment]
你的同事block-chain我也提过问题，你看他关闭了吗？
https://github.com/Phala-Network/phala-blockchain/issues/243
他没有关闭，解决也是一个链接，我觉得正常不是这样的吗？我如果解决了，我肯定会告诉他的，或者他问我有没有解决。

你自作主张关闭，我是再开一个吗？你明白我的意思吗？你说的docker问题，你不能写一行命令吗，后面的人也会知道，你不写，其他人早晚也会发一样的问题。这不是解决问题的方法。 所以我说是态度问题。

**Comment by phantom-rabbit** [comment]
恩怨情仇！！！
