### ISSUE TITLE
按照文档执行第三步 pnpm db_init 一直显示Building fetch

### ISSUE THREAD

**Issue by sidealice** [Phala-Network/runtime-bridge#32]
**Describe the bug**
按照文档说明一直执行到第三步 pnpm db_init 一直显示Building fetch

**To Reproduce**
按照文档说明

**Expected behavior**
有返回其他信息

**Screenshots**

**Host (please complete the following information):**
 - Linux distribution: ubuntu 20.04 
 - Docker version: Docker version 20.10.7, build f0df350
 - Docker Compose version:docker-compose version 1.25.0, build unknown

**Containers (please complete the following information):**
 - `poc4-prb` image hash: 没有
 - `phala-dev-node` image hash: sha256:bd2804685a1e77dfcee585227d5f37db3702e154d5a6792f3e09a38e5d89f058
 - `phala-dev-pruntime` image hash: 没有

**Additional context**
1 是否我需要在执行的命令文件夹创建data 文件夹
2 如果我用开发的方式，有没有办法直接配置一个环境文件，类似于.env这样的文件，每次进入程序读取这个文件。 我有看到env.js 但是这个是读环境变量的。不知道node的环境变量是否有项目级别可覆盖（类似于项目根目录.env这样）
var shell = require('shelljs');
shell.exec('export ENV_VARIABLE=ABRACADABRA');
可以这样去配置环境变量吗？ 如果文件夹里面有环境文件配置信息，读取他，如果没有用默认的。

**Comment by sidealice** [comment]
补充一个细节：
我在yml配置文件的文件夹打docker-compose pull
只有一个redis显示在pulling

**Comment by sidealice** [comment]
build:
      context: ../../..
      dockerfile: docker/testing/Dockerfile

我觉得这个bulid代码是否需要我们改？
因为你说不要下载。应该还是需要我们把docker文件夹放进去对吧？ 如果放进去。 context是否还是这样的？

**Comment by sidealice** [comment]
配置文件是：
`
version: "3"

services:
  fetch:
    image: phalanetwork/poc4-prb:testing
    build:
      context: ../../..
      dockerfile: docker/testing/Dockerfile
    hostname: fetch
    volumes:
      - ./data:/var/data
    environment:
      - NODE_ENV=testing
      - PHALA_MODULE=fetch
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_DB_PREFIX=/var/data
      - PHALA_MAIN_CHAIN_ENDPOINT=
      - PHALA_CHAIN_ENDPOINT=wss://127.0.0.1/ws
      - PHALA_REDIS_ENDPOINT=redis://redis:6379/

  lifecycle:
    image: phalanetwork/poc4-prb:testing
    hostname: lifecycle
    volumes:
      - ./data:/var/data
    environment:
      - NODE_ENV=testing
      - PHALA_MODULE=lifecycle
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_DB_PREFIX=/var/data
      - PHALA_MAIN_CHAIN_ENDPOINT=
      - PHALA_CHAIN_ENDPOINT=wss://127.0.0.1/ws
      - PHALA_REDIS_ENDPOINT=redis://redis:6379/

  trade:
    image: phalanetwork/poc4-prb:testing
    hostname: trade
    environment:
      - NODE_ENV=testing
      - PHALA_MODULE=trade
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_MAIN_CHAIN_ENDPOINT=
      - PHALA_CHAIN_ENDPOINT=wss://127.0.0.1/ws
      - PHALA_REDIS_ENDPOINT=redis://redis:6379/

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "no"]
    restart: always
    hostname: redis
    ports:
      - "63791:6379"
`

我本地节点rpc的查询信息是
{"jsonrpc":"2.0","result":{"currentBlock":112666,"highestBlock":112666,"startingBlock":0},"id":1}

**Comment by sidealice** [comment]
补充下：
我把redis:6379 改为127.0.0.1:6379也是一样的。

**Comment by sidealice** [comment]
只有fetch有错误。
trade和lifecycle 都可以up

**Comment by linjing666** [comment]
build:
  context: ../../..
  dockerfile: docker/testing/Dockerfile
这串配置删掉了就可以了
话说旷工节点怎么连接到这个矿池

**Comment by aixiaoo** [comment]
> build:
> context: ../../..
> dockerfile: docker/testing/Dockerfile
> 这串配置删掉了就可以了
> 话说旷工节点怎么连接到这个矿池

似乎需要跑dev的镜像
