### ISSUE TITLE
docker-compose run --no-deps --use-aliases --entrypoint "pnpm db_init" fetch , report err

### ISSUE THREAD

**Issue by gavin-ygy** [Phala-Network/runtime-bridge#36]
**Describe the bug**
~/engineering# docker-compose run --no-deps --use-aliases --entrypoint "pnpm db_init" fetch
Creating engineering_fetch_run ... done
Error responfrom daemse on: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "pnpm": executable file not found in $PATH: unknown
ERROR: 1

**To Reproduce**
1.  the os is ubuntu20
2.  Docker version 20.10.7, build f0df350
3.docker-compose version 1.29.2, build 5becea4c
4. image is : phalanetwork/phala-dev-node:latest

**Expected behavior**
根据你们的说明一步步部署，到这步就出错：
docker-compose run --no-deps --use-aliases --entrypoint "pnpm db_init" fetch
**Screenshots**

**Host (please complete the following information):**
 - Linux distribution:
 - Docker version:
 - Docker Compose version:

**Containers (please complete the following information):**
 - `poc4-prb` image hash:
 - `phala-dev-node` image hash:
 - `phala-dev-pruntime` image hash:

**Additional context**

**Comment by krhougs** [comment]
看一下你的 docker-compose.yml

**Comment by gavin-ygy** [comment]
version: "3"

x-defaults: &defaults
  volumes: &default-volume-config
    - ./data:/var/data

services:
  fetch:
    image: phalanetwork/phala-dev-node:latest
    build:
      context: ../../..
      dockerfile: docker/development/Dockerfile
    hostname: fetch
    depends_on:
      - redis
      - io
    volumes: *default-volume-config
    environment:
      - PHALA_MODULE=fetch
      - NODE_ENV=development
      - PHALA_DB_HOST=io
      - PHALA_DB_PORT_BASE=9000
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_MAIN_CHAIN_ENDPOINT=
      - PHALA_CHAIN_ENDPOINT=ws://192.168.0.103:9944/
      - PHALA_REDIS_ENDPOINT=redis://redis:6379/

  lifecycle:
    image: phalanetwork/phala-dev-node:latest
    hostname: lifecycle
    depends_on:
      - redis
      - io
    volumes: *default-volume-config
    environment:
      - PHALA_MODULE=lifecycle
      - NODE_ENV=development
      - PHALA_DB_HOST=io
      - PHALA_DB_PORT_BASE=9000
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_MAIN_CHAIN_ENDPOINT=
      - PHALA_CHAIN_ENDPOINT=ws://192.168.0.103:9944/
      - PHALA_REDIS_ENDPOINT=redis://redis:6379/

  trade:
    image: phalanetwork/phala-dev-node:latest
    hostname: trade
    depends_on:
      - redis
      - io
    volumes: *default-volume-config
    environment:
      - PHALA_MODULE=trade
      - NODE_ENV=development
      - PHALA_DB_HOST=io
      - PHALA_DB_PORT_BASE=9000
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_MAIN_CHAIN_ENDPOINT=
      - PHALA_CHAIN_ENDPOINT=ws://192.168.0.103:9944/
      - PHALA_REDIS_ENDPOINT=redis://redis:6379/

  io:
    << : *defaults
    image: phalanetwork/phala-dev-node:latest
    hostname: io
    restart: always
    environment:
      - PHALA_MODULE=io
      - NODE_ENV=development
      - PHALA_DB_HOST=io
      - PHALA_DB_PORT_BASE=9000
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_DB_PREFIX=/var/data

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "no"]
    restart: always
    hostname: redis
    ports:
      - "63791:6379"

**Comment by krhougs** [comment]
`phalanetwork/phala-dev-node:latest` 是全节点的镜像，你当然跑不起来啊。

**Comment by gavin-ygy** [comment]
那用哪个镜像？ 另外这个全节点的镜像 是不是要到另外一台机器上跑？

**Comment by gavin-ygy** [comment]
开始用你们yaml文件里面的镜像， docker-compose pull 这步就报错。

**Comment by krhougs** [comment]
phala-dev-node是节点镜像，pull报错把build那一段删掉就好了。

**Comment by gavin-ygy** [comment]
删了还是不行，在docker hub 上根本找不到 development 这个版本。你们的发布 与 研发人员严重脱节啊！

**Comment by jasl** [comment]
> 删了还是不行，在docker hub 上根本找不到 development 这个版本。你们的发布 与 研发人员严重脱节啊！

没有 development tag 试试 latest 好了吧？看了下 https://hub.docker.com/r/phalanetwork/poc4-prb/tags?page=1&ordering=last_updated 有 testing

改 : 前半部分肯定不会解决问题的（人在二里沟某处没找到在当地找找，跑八里庄那不可能找得到目标了）

**Comment by jasl** [comment]
@krhougs https://hub.docker.com/r/phalanetwork/poc4-prb/tags?page=1&ordering=last_updated 里确实没有 development tag，麻烦更新一下正确的，或者文档里提供一个规则去找可用的tag来

**Comment by krhougs** [comment]
https://github.com/Phala-Network/runtime-bridge/commit/90288ac8ce6b709b154f7e57e11a221abb811e8c
