### ISSUE TITLE
The following error appears after 'REGISTER_WORKER'

### ISSUE THREAD

**Issue by drunken005** [Phala-Network/runtime-bridge#39]
logs

{"name":"prb","hostname":"lifecycle","pid":18,"level":20,"id":"c76a8d7c-0e9a-4ce7-81a9-19ecc72205f5","nickname":"test3","phalaSs58Address":"42kZdwCBsyJ5vFdGu2oXBJQs8sdayzZoDrowM5tMrLfv2gnr","runtimeEndpoint":"http://192.168.1.4:8000","msg":"Starting worker lifecycle.","time":"2021-07-15T02:23:32.409Z","src":{"file":"file:///opt/app/src/lifecycle/lifecycle.js","line":32,"func":"addWorker"},"v":0}
{"name":"prb","hostname":"lifecycle","pid":18,"level":20,"id":"c76a8d7c-0e9a-4ce7-81a9-19ecc72205f5","nickname":"test3","phalaSs58Address":"42kZdwCBsyJ5vFdGu2oXBJQs8sdayzZoDrowM5tMrLfv2gnr","runtimeEndpoint":"http://192.168.1.4:8000","msg":"State changed.","time":"2021-07-15T02:23:32.433Z","src":{"file":"file:///opt/app/src/lifecycle/state_machine.js","line":178,"func":"onStateTransition"},"v":0}
{"name":"prb","hostname":"lifecycle","pid":18,"level":20,"workerId":"c76a8d7c-0e9a-4ce7-81a9-19ecc72205f5","state":"S_STARTING","msg":"Worker stateMachineState changed.","time":"2021-07-15T02:23:32.433Z","src":{"file":"file:///opt/app/src/lifecycle/worker.js","line":44,"func":"set stateMachineState"},"v":0}
{"name":"prb","hostname":"lifecycle","pid":18,"level":20,"id":"c76a8d7c-0e9a-4ce7-81a9-19ecc72205f5","nickname":"test3","phalaSs58Address":"42kZdwCBsyJ5vFdGu2oXBJQs8sdayzZoDrowM5tMrLfv2gnr","runtimeEndpoint":"http://192.168.1.4:8000","msg":"State changed.","time":"2021-07-15T02:23:42.317Z","src":{"file":"file:///opt/app/src/lifecycle/state_machine.js","line":178,"func":"onStateTransition"},"v":0}
{"name":"prb","hostname":"lifecycle","pid":18,"level":20,"workerId":"c76a8d7c-0e9a-4ce7-81a9-19ecc72205f5","state":"S_PENDING_SYNCHING","msg":"Worker stateMachineState changed.","time":"2021-07-15T02:23:42.317Z","src":{"file":"file:///opt/app/src/lifecycle/worker.js","line":44,"func":"set stateMachineState"},"v":0}
{"name":"prb","hostname":"lifecycle","pid":18,"level":20,"id":"c76a8d7c-0e9a-4ce7-81a9-19ecc72205f5","nickname":"test3","phalaSs58Address":"42kZdwCBsyJ5vFdGu2oXBJQs8sdayzZoDrowM5tMrLfv2gnr","runtimeEndpoint":"http://192.168.1.4:8000","msg":"Initialized pRuntime.","time":"2021-07-15T02:23:50.502Z","src":{"file":"file:///opt/app/src/lifecycle/pruntime.js","line":153,"func":"initRuntime"},"v":0}
{"name":"prb","hostname":"lifecycle","pid":18,"level":20,"id":"c76a8d7c-0e9a-4ce7-81a9-19ecc72205f5","nickname":"test3","phalaSs58Address":"42kZdwCBsyJ5vFdGu2oXBJQs8sdayzZoDrowM5tMrLfv2gnr","runtimeEndpoint":"http://192.168.1.4:8000","msg":"State changed.","time":"2021-07-15T02:23:54.317Z","src":{"file":"file:///opt/app/src/lifecycle/state_machine.js","line":178,"func":"onStateTransition"},"v":0}
{"name":"prb","hostname":"lifecycle","pid":18,"level":20,"workerId":"c76a8d7c-0e9a-4ce7-81a9-19ecc72205f5","state":"S_ERROR","msg":"Worker stateMachineState changed.","time":"2021-07-15T02:23:54.317Z","src":{"file":"file:///opt/app/src/lifecycle/worker.js","line":44,"func":"set stateMachineState"},"v":0}
{"name":"prb","hostname":"lifecycle","pid":18,"level":50,"fromState":"S_PENDING_SYNCHING","toState":"S_ERROR","workerId":"c76a8d7c-0e9a-4ce7-81a9-19ecc72205f5","phalaSs58Address":"42kZdwCBsyJ5vFdGu2oXBJQs8sdayzZoDrowM5tMrLfv2gnr","msg":"Error: phala.WrongMREnclave:  Wrong MRENCLAVE\n    at Queue._onMessage (/opt/app/node_modules/.pnpm/bee-queue@1.4.0/node_modules/bee-queue/lib/queue.js:138:22)\n    at RedisClient.emit (events.js:375:28)\n    at return_pub_sub (/opt/app/node_modules/.pnpm/redis@2.8.0/node_modules/redis/index.js:786:18)\n    at RedisClient.return_reply (/opt/app/node_modules/.pnpm/redis@2.8.0/node_modules/redis/index.js:833:9)\n    at JavascriptRedisParser.returnReply (/opt/app/node_modules/.pnpm/redis@2.8.0/node_modules/redis/index.js:192:18)\n    at JavascriptRedisParser.execute (/opt/app/node_modules/.pnpm/redis-parser@2.6.0/node_modules/redis-parser/lib/parser.js:574:12)\n    at Socket.<anonymous> (/opt/app/node_modules/.pnpm/redis@2.8.0/node_modules/redis/index.js:274:27)\n    at Socket.emit (events.js:375:28)\n    at addChunk (internal/streams/readable.js:290:12)\n    at readableAddChunk (internal/streams/readable.js:265:9)","time":"2021-07-15T02:23:54.317Z","src":{"file":"file:///opt/app/src/lifecycle/state_machine.js","line":126,"func":"onError"},"v":0}

**Comment by drunken005** [comment]
cc @krhougs Please.

**Comment by krhougs** [comment]
Please check if the image hash of pruntime equals to the value in https://github.com/Phala-Network/runtime-bridge/releases/tag/v0.1.0-beta.1

**Comment by drunken005** [comment]
> Please check if the image hash of pruntime equals to the value in https://github.com/Phala-Network/runtime-bridge/releases/tag/v0.1.0-beta.1

Already resolved. Thx...
