### ISSUE TITLE
cat data.json | docker-compose run --no-deps --use-aliases --entrypoint "pnpm add_machines" lifecycle， report "Error: getaddrinfo EAI_AGAIN io"

### ISSUE THREAD

**Issue by gavin-ygy** [Phala-Network/runtime-bridge#42]
**Describe the bug**
1. Docker version 20.10.7
2. docker-compose version 1.29.2
3. ubuntu20
4. data.json
{
  "machines": [
    {
      "payoutAddress": "45xrnT6yZQg7fhLzcokPuF2CthsXxQgJkGJoasdMRzJafzSE",
      "nickname": "i7-test",
      "runtimeEndpoint": "http://192.168.0.101:8000"
    }
  ]
}

5.  node image
phalanetwork/phala-dev-node        latest    bd2804685a1e   3 weeks ago   394MB
phalanetwork/phala-poc4-node       latest    bd2804685a1e   3 weeks ago   394MB

6.  the machine just installed the solo Tee package yesterday,  the image  phala-dev-node and phala-poc4-node  is the same. So i use the cmd 'phala start node and phala start pruntime '  . (ip is 192.168.0.101)

7. cat data.json | docker-compose run --no-deps --use-aliases --entrypoint "pnpm add_machines" lifecycle   in the rpc server(192.168.0.103).  The error is the following:
cat data.json | docker-compose run --no-deps --use-aliases --entrypoint "pnpm add_machines" lifecycle
Creating engineering_lifecycle_run ... done

> @phala/runtime-bridge@1.0.0 add_machines /opt/app
> node --experimental-json-modules --es-module-specifier-resolution=node --harmony-top-level-await src/scripts/add_machines

{"name":"prb","hostname":"lifecycle","pid":18,"level":30,"loggerLevel":20,"msg":"Logging Enabled.","time":"2021-07-16T07:42:02.748Z","src":{"file":"file:///opt/app/src/utils/logger.js","line":10},"v":0}
Error: getaddrinfo EAI_AGAIN io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'io'
}
{"name":"prb","hostname":"lifecycle","pid":18,"level":50,"port":9003,"host":"io","msg":"Error: getaddrinfo EAI_AGAIN io\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {\n  errno: -3001,\n  code: 'EAI_AGAIN',\n  syscall: 'getaddrinfo',\n  hostname: 'io'\n}","time":"2021-07-16T07:42:03.026Z","src":{"file":"file:///opt/app/src/io/db.js","line":65},"v":0}
{"name":"prb","hostname":"lifecycle","pid":18,"level":50,"port":9003,"host":"io","msg":"true","time":"2021-07-16T07:42:03.029Z","src":{"file":"file:///opt/app/src/io/db.js","line":69},"v":0}

**To Reproduce**

**Expected behavior**

**Screenshots**

**Host (please complete the following information):**
 - Linux distribution:
 - Docker version:
 - Docker Compose version:

**Docker Compose configuration**
Provide your working `docker-compose.yml` if related to deployment.

**Containers (please complete the following information):**
 - `poc4-prb` image hash:
 - `phala-dev-node` image hash:
 - `phala-dev-pruntime` image hash:

**Additional context**

**Comment by krhougs** [comment]
the io service should be running when importing machines
