### ISSUE TITLE
no persistant state issue (HIGH)

### ISSUE THREAD

**Issue by PHA-SYSOPS** [Phala-Network/runtime-bridge#48]
Have a running setup with 1 miner, now add a 2nd miner
as per requirement a restart of PRB is required, after the restart the 2nd miner will start to sync and works, but the first miner BREAKS:
69
S_SYNCHING
1629058730039 - State changed from S_STARTING to S_SYNCHING
4294967295

Then is stuck. Pruntime needs a restart to resolve this, but then a PRB restarted is needed to ... which in turn kills miner2

**Comment by krhougs** [comment]
You just need to wait for a more seconds until the status be read and verified from pruntime
