### ISSUE TITLE
unhandled error on empty funds on pool

### ISSUE THREAD

**Issue by PHA-SYSOPS** [Phala-Network/runtime-bridge#50]
{"name":"prb","hostname":"trade","pid":18,"level":40,"queueName":"prbmq__69","msg":"Error: phalaMining.MinerNotMining: undefined\n    at Queue._onMessage (/opt/app/node_modules/.pnpm/bee-queue@1.4.0/node_modules/bee-queue/lib/queue.js:138:22)\n    at RedisClient.emit (events.js:400:28)\n    at return_pub_sub (/opt/app/node_modules/.pnpm/redis@2.8.0/node_modules/redis/index.js:786:18)\n    at RedisClient.return_reply (/opt/app/node_modules/.pnpm/redis@2.8.0/node_modules/redis/index.js:833:9)\n    at JavascriptRedisParser.returnReply (/opt/app/node_modules/.pnpm/redis@2.8.0/node_modules/redis/index.js:192:18)\n    at JavascriptRedisParser.execute (/opt/app/node_modules/.pnpm/redis-parser@2.6.0/node_modules/redis-parser/lib/parser.js:574:12)\n    at Socket.<anonymous> (/opt/app/node_modules/.pnpm/redis@2.8.0/node_modules/redis/index.js:274:27)\n    at Socket.emit (events.js:400:28)\n    at addChunk (internal/streams/readable.js:290:12)\n    at readableAddChunk (internal/streams/readable.js:265:9) Job #32 failed with error phalaMining.MinerNotMining: undefined.","time":"2021-08-16T08:34:54.526Z","v":0}
{"name":"prb","hostname":"trade","pid":18,"level":40,"err":{"message":"phalaMining.MinerNotMining: undefined","name":"Error","stack":"Error: phalaMining.MinerNotMining: undefined\n    at Queue._onMessage (/opt/app/node_modules/.pnpm/bee-queue@1.4.0/node_modules/bee-queue/lib/queue.js:138:22)\n    at RedisClient.emit (events.js:400:28)\n    at return_pub_sub (/opt/app/node_modules/.pnpm/redis@2.8.0/node_modules/redis/index.js:786:18)\n    at RedisClient.return_reply (/opt/app/node_modules/.pnpm/redis@2.8.0/node_modules/redis/index.js:833:9)\n    at JavascriptRedisParser.returnReply (/opt/app/node_modules/.pnpm/redis@2.8.0/node_modules/redis/index.js:192:18)\n    at JavascriptRedisParser.execute (/opt/app/node_modules/.pnpm/redis-parser@2.6.0/node_modules/redis-parser/lib/parser.js:574:12)\n    at Socket.<anonymous> (/opt/app/node_modules/.pnpm/redis@2.8.0/node_modules/redis/index.js:274:27)\n    at Socket.emit (events.js:400:28)\n    at addChunk (internal/streams/readable.js:290:12)\n    at readableAddChunk (internal/streams/readable.js:265:9)"},"msg":"Job #32 failed with error.","time":"2021-08-16T08:34:54.526Z","v":0}

**Comment by krhougs** [comment]
fixed in https://github.com/Phala-Network/runtime-bridge/releases/tag/v0.3.0-beta.1
