### ISSUE TITLE
Reschedule the benchmark if Pinit is lower than expected

### ISSUE THREAD

**Issue by HikaruG** [Phala-Network/runtime-bridge#71]
## Summary: 

I would like to specify a  **Pmin** that would restart the Benchmark process if the benchmark's results is lower. 

## Reason behind this feature: 

Currently, the benchmark process is directly followed by the start of the mining process of a worker, with the only exception  being:    **Pinit < 50**

However, it's very much possible for a benchmark to be higher than 50, but still way lower than the "theoretical" value one expects. 
For instance, I had a worker with a Pinit=400 where in theory I should have gotten 1200. 

## Potential ways to solve this issue: 

By swapping the below hard coded value to a variable, which could then be set using an Env variable for instance could solve this. 

https://github.com/Phala-Network/runtime-bridge/blob/ea12f581650cfe8479d3c7168a82b2b2f197b7aa/src/lifecycle/state_machine.js#L112
  
I'm open to discuss about this topic, and explore alternatives if there are any, or even discuss about the validity of such feature/potential downsides.

**Comment by krhougs** [comment]
Add envvar `PHALA_MIN_BENCH_SCORE` to lifecycle container

https://github.com/Phala-Network/runtime-bridge/commit/36811290743454f1b7d1956251db257e89b9cdb9
