### ISSUE TITLE
Don't save unencrypted private keys of pool owner

### ISSUE THREAD

**Issue by krhougs** [Phala-Network/runtime-bridge#74]
For safety propose, unencrypted private keys of pool owner should not be saved in the database.

To solve this, an optional encryption should be applied:
1. an X.509 certificate should be generated before setting up PRB;
2. PRB lifecycle should generate a passphrase to unlock pool's owner account, the polkadot account keypair should be protected by the passphrase;
3. Saved account and its passphrase should be encrypted with the certificate before writing to the database;
4. PRB trade use the certificate's private key to decrypt the account information.

**Comment by h4x3rotab** [comment]
Maybe easier to use Vault directly
