### ISSUE TITLE
documentation link in README.md does not link to any documentation about PRB

### ISSUE THREAD

**Issue by yayoi-k** [Phala-Network/runtime-bridge#81]
README.md contains the following line and link which does not go to any actual content about PRB:

"Documents: https://wiki.phala.network/en-us/docs/prb/"

The only documentation on PRB that I can find is this link which has a small amount of content and no actual docker commands:
https://wiki.phala.network/en-us/maintain/khala-mining/runtime-bridge/

At one point in time I believe there was PRB 1.0 documentation that contained the docker commands.

**Comment by krhougs** [comment]
Sorry for that the auto redirection is not working with our new wiki site. These link will be updated with next release:
For PRB v0.x: https://wiki.phala.network/en-us/maintain/prb/docker-compose-example/
For PRB v2: https://github.com/Phala-Network/runtime-bridge/wiki/Deployment-Guide-for-Runtime-Bridge-2
