### ISSUE TITLE
data_provider No response received from RPC endpoint in 30s (data_provider and NODE, not on the same machine)

### ISSUE THREAD

**Issue by Gitman001** [Phala-Network/runtime-bridge#83]
![image](https://user-images.githubusercontent.com/64299920/163779811-01cb3f3f-c9ab-4388-b868-62123807055a.png)

![image](https://user-images.githubusercontent.com/64299920/163779852-ceedd982-ca29-4c31-9ff0-45ec291698cb.png)

The khala chain height is no longer synchronized, and the ksm height is normal

Version:
khala-node --> v0.1.13
prb-data-provider --> next

**Comment by krhougs** [comment]
Your log indicated that the data provider failed to receive keepalive response from the khala node.
Is there any error related output in the khala-node?

**Comment by Gitman001** [comment]
> 您的日志指示数据提供程序无法从 khala 节点接收到保持活动状态的响应。 khala 节点中是否有任何与错误相关的输出？
sir , no error output in NODE log
![image](https://user-images.githubusercontent.com/64299920/163791728-7369f74a-d2e9-42e9-830c-0157db0fbb97.png)

**Comment by krhougs** [comment]
麻烦执行以下步骤来获得更详细的日志：
1. 完全关闭所有组件
2. 在`docker-compose.yml`里给khala-node容器加上环境变量：`RUST_LOG="trace,soketto=warn,jsonrpsee_ws_client=warn,remote-ext=warn,trie=warn,wasmtime_cranelift=warn"`
3. 启动khala-node和data_provider，等待问题复现
4. 待问题复现后导出并上传完整log（可以使用gist或者ubuntu pastebin）

这个问题在我们的测试机上没有复现，方便的话麻烦告知一下包括硬件型号的详细机器参数。

**Comment by Gitman001** [comment]
> 麻烦执行以下步骤来获得更详细的日志：
> 
> 1. 完全关闭所有组件
> 2. 在`docker-compose.yml`里给khala-node容器加上环境变量：`RUST_LOG="trace,soketto=warn,jsonrpsee_ws_client=warn,remote-ext=warn,trie=warn,wasmtime_cranelift=warn"`
> 3. 启动khala-node和data_provider，等待问题复现
> 4. 待问题复现后导出并上传完整log（可以使用gist或者ubuntu pastebin）
> 
> 这个问题在我们的测试机上没有复现，方便的话麻烦告知一下包括硬件型号的详细机器参数。

--------------------------------------------------------------------------------------------------------
不确定NODE日志是否全面，如果没有体现错误日志，请联系我重新发送

[NODE + data_provider.zip](https://github.com/Phala-Network/runtime-bridge/files/8511920/NODE.%2B.data_provider.zip)

内核版本：5.4.0-91-generic
系统版本：Ubuntu 18.04.6 LTS
主板：B460M
CPU：i9-10850k
内存：三星16G

**Comment by krhougs** [comment]
@h4x3rotab @kvinwang

**Comment by krhougs** [comment]
请问目前运行的prb版本是dockerhub上最新的吗？如果不是，更新后问题是否依然存在？

**Comment by krhougs** [comment]
@Gitman001 我们试了好久均无法复现这个问题，请问：
- 在出现这个卡住的情况时，khala node是否已经同步到了网络高度？
- 在出现这个卡住的情况时，finalized高度和已同步的高度相差多少？

同时，请问是否已经排查网络问题？某些不靠谱的路由器可能会对TCP长连接造成影响。

**Comment by h4x3rotab** [comment]
请尝试一下再出现这个问题的时候仅重启PRB能否缓解问题。如果不能，可以试试看重启节点能否缓解问题。看起来问题应该发生在节点端，所以有必要确认它是一个节点层面的问题，还是websocket session层面的问题

**Comment by Gitman001** [comment]
> 请问目前运行的prb版本是dockerhub上最新的吗？如果不是，更新后问题是否依然存在？

**Comment by Gitman001** [comment]
在当时出现这个问题时，PRB和NODE是docker hub最新版本

**Comment by Gitman001** [comment]
> 请尝试一下再出现这个问题的时候仅重启PRB能否缓解问题。如果不能，可以试试看重启节点能否缓解问题。看起来问题应该发生在节点端，所以有必要确认它是一个节点层面的问题，还是websocket session层面的问题

当我重启NODE和PRB后，会恢复。直到问题再度出现

**Comment by Gitman001** [comment]
> @Gitman001 我们试了好久均无法复现这个问题，请问：
> 
> * 在出现这个卡住的情况时，khala node是否已经同步到了网络高度？
> * 在出现这个卡住的情况时，finalized高度和已同步的高度相差多少？
> 
> 同时，请问是否已经排查网络问题？某些不靠谱的路由器可能会对TCP长连接造成影响。

目前来看，卡住的时候，NODE高度是最新的，似乎只有prb的khala高度不再继续同步

**Comment by h4x3rotab** [comment]
那么应该是websocket session层面的问题，因为重启prb之后能缓解

**Comment by Gitman001** [comment]
> 那么应该是websocket session层面的问题，因为重启prb之后能缓解

好的，谢谢

矿池里有一个node，两个data_provider，两个lifecycle，分别运行不同池子的矿工。昨天把一个prb和一个lifecycle关掉了，到第二天还没出现超时的问题。请问两个data-provider模块能否互相指定呢？图中的18888端口是由谁来提供的呢？哪个模块连接它呢？两个data_provider能不能互连呢？
![image](https://user-images.githubusercontent.com/64299920/164966307-f41d0425-a5bf-4a3a-809e-7e3994f5e726.png)

**Comment by krhougs** [comment]
你自己把Issue关了，我们看不到回复提醒。
没太看懂“请问两个data-provider模块能否互相指定呢？”指的是什么。

**Comment by Gitman001** [comment]
> 你自己把Issue关了，我们看不到回复提醒。 没太看懂“请问两个data-provider模块能否互相指定呢？”指的是什么。

谢谢您的回复。
“请问两个data-provider模块能否互相指定呢？ -> 使用了2台data-provider的机器，共用1个node
分别在data-provider模块中，PHALA_WALKIE_BOOT_NODES填写了另一个data-provider模块的ip和p2p的地址，写法是否是正确的？
当停止运行其中1台data-provider模块后，超时30s的问题，有所改善，后续仍然有时出现，有时是1天2次。近期，超时问题出现的频率在减少。
离最近的1次超时问题，已经平稳运行2天了。
