### ISSUE TITLE
prb dp logs Subprocess exited

### ISSUE THREAD

**Issue by 1613557499** [Phala-Network/runtime-bridge#84]
![image](https://user-images.githubusercontent.com/86406225/166207871-d70e4471-2cc4-4389-9ead-9d1b55f89fdb.png)
![image](https://user-images.githubusercontent.com/86406225/166208052-46ce0b00-5b9b-44d2-a7ac-7455903ba1b5.png)

**Comment by krhougs** [comment]
Duplicated to https://github.com/Phala-Network/runtime-bridge/issues/83
