### ISSUE TITLE
Feature Request: Define fallback parachain/relaychain nodes for frequent "block body not found" issues

### ISSUE THREAD

**Issue by Nexus2k** [Phala-Network/runtime-bridge#90]
We're currently seeing frequent occasions of "block body not found" where we need to switch from our local khala-node to an upstream provided one, synch a few blocks and then switch back. This is a quite bothersome and manual labor task. It would be great if the data_provider could accept a new FALLBACK_PHALA_PARENT_CHAIN_ENDPOINT and FALLBACK_PHALA_CHAIN_ENDPOINT environment variables that are being used when the regular node caused any issue with block ingestion.

**Comment by krhougs** [comment]
Now the problem has been solved by the upcoming PRBv3 release:
https://phalanetwork.notion.site/Runtime-Bridge-3-Beta-Guide-a6321283ef544aab950660f194cfc702
